name: CI

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: '0 1 27 * *'

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        components: clippy

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Check Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
